# Generated by Django 5.2 on 2025-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='addresses',
            field=models.ManyToManyField(null=True, related_name='suppliers', to='core.address'),
        ),
    ]
