# Generated by Django 5.2 on 2025-04-15 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_warehouse_warehouse_manager'),
        ('orders', '0004_alter_order_created_by'),
        ('users', '0002_alter_supplier_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addresses',
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='core.warehouse'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='addresses',
            field=models.ManyToManyField(related_name='suppliers', to='core.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Adminstration'), ('internal', 'Internal User'), ('driver', 'Driver'), ('supplier', 'Supplier'), ('customer', 'Customer')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
