# Generated by Django 5.2 on 2025-04-18 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_user'),
        ('users', '0003_remove_user_addresses_user_manager_user_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='addresses',
            field=models.ManyToManyField(null=True, related_name='suppliers', to='core.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Adminstration'), ('internal', 'Internal User'), ('supplier', 'Supplier'), ('customer', 'Customer')], max_length=20),
        ),
    ]
