# Generated by Django 5.2 on 2025-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer_employee_warehouseemployees'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(db_comment='determines if customer is active with this company', default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(db_comment='determines if supplier is active with this company', default=True),
        ),
    ]
