# Generated by Django 5.2 on 2025-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_active_supplier_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(db_comment='determines if user can still login to the application', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Adminstration'), ('employee', 'Employee'), ('supplier', 'Supplier'), ('customer', 'Customer')], max_length=20),
        ),
    ]
