# Generated by Django 5.2 on 2025-04-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customer_company_supplier_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='domain_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
