# Generated by Django 5.2 on 2025-04-26 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_supplier_created_by_supplier_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 22, 17, 41, 542015)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 22, 17, 57, 403818)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text="Keep it empty it you don't want to change it.", max_length=128),
        ),
    ]
