# Generated by Django 5.2 on 2025-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customer_created_at_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='leh la', max_length=100),
            preserve_default=False,
        ),
    ]
