# Generated by Django 5.2 on 2025-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_supplier_created_by_alter_supplier_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
