# Generated by Django 5.2 on 2025-06-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customer_updated_at_alter_supplier_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('admin', 'Adminstration'), ('warehouse_manager', 'Warehouse Manager'), ('driver', 'Driver'), ('internal', 'Internal Employee')], max_length=20),
        ),
    ]
