# Generated by Django 5.2 on 2025-07-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_routingrule_via_warehouses_and_more'),
        ('users', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse'),
        ),
    ]
