# Generated by Django 5.2 on 2025-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_employee_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(db_comment='determines if customer is active with this company', default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(db_comment='False means employee is not working anymore for this company', default=1),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(db_comment='determines if supplier is active with this company', default=1),
        ),
        migrations.AlterField(
            model_name='warehouseemployees',
            name='active',
            field=models.BooleanField(db_comment='Bool field determines of the employee is still working under this warehouse', default=1),
        ),
    ]
