# Generated by Django 5.2 on 2025-07-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customer_active_alter_employee_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(db_comment='If employee is still working for the company or not', default=1),
        ),
    ]
