# Generated by Django 5.2 on 2025-08-02 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_employee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse_manager', 'Warehouse Manager'), ('driver', 'Driver'), ('internal_user', 'Internal User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer'), ('employee', 'Employee')], max_length=20),
        ),
    ]
