# Generated by Django 5.2 on 2025-08-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_deliverypricelist_order_delivery_pricelist_and_more'),
        ('users', '0022_alter_employee_employee_type_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivery_pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverypricelist'),
        ),
    ]
