# Generated by Django 5.2 on 2025-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_supplier_delivery_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Commission in USD (drivers only)', max_digits=10, null=True),
        ),
    ]
