# Generated by Django 5.2 on 2025-10-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_stocklocation_active'),
        ('users', '0024_employee_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='addresses',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='core.address'),
        ),
    ]
