# Generated by Django 5.2 on 2026-02-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_account'),
        ('users', '0025_remove_supplier_addresses_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='core.account'),
        ),
    ]
