# Generated by Django 5.2 on 2026-02-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_account'),
        ('users', '0026_supplier_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='account',
        ),
        migrations.AddField(
            model_name='supplier',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='core.account'),
        ),
    ]
