# Generated by Django 5.2 on 2026-02-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_warehouse_accounts'),
        ('users', '0027_remove_supplier_account_supplier_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='employee', to='core.account'),
        ),
    ]
