# Generated by Django 5.2 on 2026-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_warehouse_accounts'),
        ('users', '0028_employee_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='customers', to='core.account'),
        ),
    ]
