# Generated by Django 5.2 on 2025-04-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_address',
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_orders', to='core.address'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='receiver',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('warehouse', 'Warehouse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='sender',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('warehouse', 'Warehouse')], max_length=20),
        ),
    ]
