# Generated by Django 5.2 on 2025-04-29 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_active_company_currency_warehouse_active'),
        ('orders', '0004_alter_order_created_by'),
        ('users', '0015_alter_customer_updated_at_alter_supplier_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=20)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='tracking_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('done', 'Done')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending_pickup', 'Pending Pickup'), ('in_warehouse', 'In Warehouse'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=30),
        ),
        migrations.RenameField(
            model_name='ordertracking',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='source_location',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='effective_date',
            field=models.DateTimeField(help_text='Date at which the Order has been delivered or cancelled.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_comment='Creation Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_delivery_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tracking_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='effective_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='recipient_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_address', to='core.address'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='sender_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_address', to='core.address'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tracking_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_address', to='core.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_address', to='core.address'),
        ),
        migrations.RenameModel(
            old_name='OrderRequirments',
            new_name='PackageRequirments',
        ),
        migrations.CreateModel(
            name='OrderPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barcode', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packages', to='orders.order')),
                ('package_requirment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.packagerequirments')),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.packagetype')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.DeleteModel(
            name='OrderStatusRef',
        ),
    ]
