# Generated by Django 5.2 on 2025-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_packagetype_alter_ordertracking_tracking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackages',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
