# Generated by Django 5.2 on 2025-05-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderpackages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
