# Generated by Django 5.2 on 2025-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackages',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderpackages',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderpackages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderpackages',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderpackages',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
