# Generated by Django 5.2 on 2025-05-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderpackages_barcode_and_more'),
        ('users', '0015_alter_customer_updated_at_alter_supplier_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
    ]
