# Generated by Django 5.2 on 2025-05-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stocklocation'),
        ('orders', '0010_ordertracking_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='recipient_address',
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_receiver', to='core.stocklocation'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='receiver_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_address', to='core.address'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_sender', to='core.stocklocation'),
        ),
    ]
