# Generated by Django 5.2 on 2025-05-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_ordertracking_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='confirmed_by_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='confirmed_by_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('pending_pickup', 'Pending Pickup'), ('in_warehouse', 'In Warehouse'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=30),
        ),
    ]
