# Generated by Django 5.2 on 2025-06-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='tracking_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
