# Generated by Django 5.2 on 2025-06-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='reference',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('picked_up', 'Picked Up')], default='requested', max_length=20),
        ),
    ]
