# Generated by Django 5.2 on 2025-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderrequest_reference_alter_orderrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
