# Generated by Django 5.2 on 2025-06-19 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_warehouse_active'),
        ('orders', '0017_alter_orderrequest_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Associated Warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse'),
        ),
    ]
