# Generated by Django 5.2 on 2025-06-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_order_price_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Associated Warehouse',
            new_name='warehouse',
        ),
    ]
