# Generated by Django 5.2 on 2025-06-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_rename_associated_warehouse_order_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='DRAFT', max_length=255, null=True),
        ),
    ]
