# Generated by Django 5.2 on 2025-07-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_warehouse_active'),
        ('orders', '0022_order_order_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='warehouse',
            new_name='pickup_warehouse',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_warehouse', to='core.warehouse'),
        ),
    ]
