# Generated by Django 5.2 on 2025-07-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_rename_warehouse_order_pickup_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('pending_pickup', 'Pending Pickup'), ('pickup_confirmed', 'Pickup Confirmed'), ('in_warehouse', 'In Warehouse'), ('in_warehouse_transit', 'In Transit to Warehouse'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=30),
        ),
    ]
