# Generated by Django 5.2 on 2025-08-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverypricelist'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='delivery_pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverypricelist'),
        ),
        migrations.CreateModel(
            name='DeliveryPriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.packagetype')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_items', to='orders.deliverypricelist')),
            ],
        ),
    ]
