# Generated by Django 5.2 on 2025-08-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_cancelled_at_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
