# Generated by Django 5.2 on 2025-09-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackages',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverypricelistitem'),
        ),
    ]
