# Generated by Django 5.2 on 2025-09-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_orderpackages_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetype',
            name='default',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='fees',
        ),
    ]
