# Generated by Django 5.2 on 2025-09-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_remove_packagetype_default_remove_packagetype_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_children', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='exchanged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_exchanged',
            field=models.BooleanField(default=False),
        ),
    ]
