# Generated by Django 5.2 on 2025-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_exchange_parent_order_exchange_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='effective_date',
            field=models.DateTimeField(null=True),
        ),
    ]
