# Generated by Django 5.2 on 2025-09-30 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_order_planned_route'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderphoneverification',
            new_name='orders_orde_order_i_98d836_idx',
            old_name='orders_order_status_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='driver_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('pending_pickup', 'Pending Pickup'), ('pickup_confirmed', 'Pickup Confirmed'), ('in_warehouse', 'In Warehouse'), ('in_warehouse_transit', 'In Transit to Warehouse'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('out_for_supplier', 'Out Returning to Supplier')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderphoneverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
