# Generated by Django 5.2 on 2025-10-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_stocklocation_active'),
        ('orders', '0034_rename_orders_order_status_idx_orders_orde_order_i_98d836_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypricelistitem',
            name='destination_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_items', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='deliverypricelistitem',
            name='source_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_items', to='core.warehouse'),
        ),
    ]
