# Generated by Django 5.2 on 2025-11-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_deliverypricelistitem_destination_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_direct_to_warehouse',
            field=models.BooleanField(default=False, help_text='Tick if the driver brought the order directly to the warehouse.'),
        ),
    ]
