# Generated by Django 5.2 on 2025-11-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_address_building_alter_address_street_and_more'),
        ('orders', '0036_order_is_direct_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_secondary', to='core.currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price_secondary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
