# Generated by Django 5.2 on 2025-04-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_user'),
        ('users', '0009_supplier_domain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supplier'),
        ),
    ]
