# Generated by Django 5.2 on 2025-04-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_address_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='supplier',
        ),
    ]
