# Generated by Django 5.2 on 2025-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_active_company_currency_warehouse_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='floor',
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
