# Generated by Django 5.2 on 2025-06-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stocklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
