# Generated by Django 5.2 on 2025-07-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_routingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingrule',
            name='via_warehouses',
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_from', to='core.warehouse'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_to', to='core.warehouse'),
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.routingrule')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
