# Generated by Django 5.2 on 2025-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_routingrule_via_warehouses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
