# Generated by Django 5.2 on 2025-07-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_company_active'),
        ('users', '0020_alter_customer_active_alter_employee_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_manager', to='users.employee'),
        ),
    ]
