# Generated by Django 5.2 on 2025-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_numbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
