# Generated by Django 5.2 on 2026-02-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='warehouses', to='core.account'),
        ),
    ]
